apiVersion: v1
kind: List
items:

# Declare the ingress for these resources
  - apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: test
    spec:
      backend:
        serviceName: nginx-svc
        servicePort: 80

# Declare the service, using nginx as selector in port 80
  - apiVersion: v1
    kind: Service
    metadata:
      name: nginx-svc
    spec:
      selector:
        app: nginx
      ports:
      - name: default
        protocol: TCP
        port: 80
        targetPort: 80
    type: NodePort

# Declare the deployment
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: nginx-deployment
      labels:
        app: nginx
    spec:
      replicas: 3
      selector:
        matchLabels:
          app: nginx
      template:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
          - name: nginx
            image: nginx:latest
            ports:
            - containerPort: 80
