apiVersion: v1
kind: List
items:

# Declare the ingress for these resources
  - apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: rev-dsc-ingress
    spec:
      backend:
        serviceName: rev-dsc-svc
        servicePort: 80

# Declare the service, using nginx as selector in port 80
  - apiVersion: v1
    kind: Service
    metadata:
      name: rev-dsc-svc
    spec:
      selector:
        app: rev-dsc
      type: NodePort
      ports:
      - name: default
        protocol: TCP
        port: 80
        targetPort: 8081

# Declare the deployment
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: rev-dsc-deployment
      labels:
        app: rev-dsc
    spec:
      replicas: 3
      selector:
        matchLabels:
          app: rev-dsc
      template:
        metadata:
          labels:
            app: rev-dsc
        spec:
          containers:
          - name: rev-dsc
            image: gcr.io/gke-node-replications/revdsc:0.1
            env:
            - name: POD_CIDR
              value: "10.16.1.6"
            ports:
            - containerPort: 8081
