apiVersion: apps/v1
kind: Deployment
metadata:
  name: get-pod-info-deployment
  labels:
    app: get-pod-info
spec:
  replicas: 3
  selector:
    matchLabels:
      app: get-pod-info
  template:
    metadata:
      labels:
        app: get-pod-info
    spec:
      containers:
      - name: get-info
        image: [TODO]    
      env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name        
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
          ports:
            - containerPort: 8081        